### PR TITLE
fix(deps): update markdown to v6.0.3

### LINKED ISSUE #894: high severity vulnerability
Latest @jobber/components (v2.83.0) introduces a high severity vulnerability to our application:

170662385-2a47474e-59df-4e71-ac7c-6f4f7d6abbd9

### PR DESCRIPTION
**Pull request by darryltec**
### Added

- 

### Changed

- Bumped react-markdown to v6 which removes the `trim` subdependency
image

  - Bumping to latest version breaks jest because of some ESM issue

### Deprecated

- 

### Removed

- 

### Fixed

- Fixes #894

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

File: packages/components/src/Markdown/Markdown.tsx [hunk 1]
```diff
@@ -23,69 +23,69 @@ interface MarkdownProps {
...
-    />
+    <Tag>
+      <ReactMarkdown
+        {...props}
+        linkTarget={externalLink ? "_blank" : undefined}
+        components={{
+          p: renderParagraph,
+          strong: renderStrong,
+          em: renderEmphasis,
+          h1: renderHeading(1),
```
Comment (MichaelParadis) [inline packages/components/src/Markdown/Markdown.tsx:58]: For reference this is the replacements that are defined.
https://github.com/remarkjs/react-markdown/blob/main/changelog.md#600---2021-04-15

Comment (MichaelParadis) [inline packages/components/src/Markdown/Markdown.tsx:58]: For reference this is the replacements that are defined.
https://github.com/remarkjs/react-markdown/blob/main/changelog.md#600---2021-04-15

File: packages/components/src/Markdown/Markdown.tsx [hunk 2]
```diff
@@ -23,69 +23,69 @@ interface MarkdownProps {
...
-      linkTarget={externalLink ? "_blank" : undefined}
-      renderers={{
-        root: renderWrapper,
-        paragraph: renderParagraph,
-        emphasis: renderEmphasis,
-        strong: renderStrong,
-        heading: renderHeading,
-      }}
-    />
+    <Tag>
```
Comment (MichaelParadis) [inline packages/components/src/Markdown/Markdown.tsx:50]: This line is due to the new update tells  you to wrap the markdown component instead of passing a root component.

**Review by MichaelParadis — APPROVED** [review]
LGTM!
